package com.software.ddk.coloredfire.integration;

import com.software.ddk.coloredfire.ColoredFireMod;
import com.terraformersmc.terrestria.init.TerrestriaBlocks;
import net.fabricmc.loader.FabricLoader;

public class TerrestriaIntegration {

    public static boolean isLoaded(){
        return FabricLoader.INSTANCE.isModLoaded("terrestria");
    }

    public static Object[][] getFlammables(){
        ColoredFireMod.COLOREDLOG.info("[Colored Flames] Terrestria detected, adding flammables integration");
        //todo - check disabled blocks to match latest curseforge release.
        return new Object[][]{
                {TerrestriaBlocks.CYPRESS.leaves, 5, 20},
                {TerrestriaBlocks.CYPRESS.log, 5, 20},
                {TerrestriaBlocks.CYPRESS.planks, 5, 20},
                {TerrestriaBlocks.CYPRESS.slab, 5, 20},
                {TerrestriaBlocks.CYPRESS.strippedLog, 5, 20},
                {TerrestriaBlocks.CYPRESS.strippedWood, 5, 20},
                {TerrestriaBlocks.CYPRESS.wood, 5, 20},
                //{TerrestriaBlocks.CYPRESS.button, 5, 20},
                //{TerrestriaBlocks.CYPRESS.door, 5, 20},
                //{TerrestriaBlocks.CYPRESS.trapdoor, 5, 20},
                {TerrestriaBlocks.CYPRESS.fence, 5, 20},
                {TerrestriaBlocks.CYPRESS.fenceGate, 5, 20},
                //{TerrestriaBlocks.CYPRESS.sign, 5, 20},
                //{TerrestriaBlocks.CYPRESS.wallSign, 5, 20},
                //{TerrestriaBlocks.CYPRESS.pressurePlate, 5, 20},
                //{TerrestriaBlocks.CYPRESS.stairs, 5, 20},

                {TerrestriaBlocks.HEMLOCK.leaves, 5, 20},
                {TerrestriaBlocks.HEMLOCK.log, 5, 20},
                {TerrestriaBlocks.HEMLOCK.planks, 5, 20},
                {TerrestriaBlocks.HEMLOCK.slab, 5, 20},
                {TerrestriaBlocks.HEMLOCK.strippedLog, 5, 20},
                {TerrestriaBlocks.HEMLOCK.strippedWood, 5, 20},
                {TerrestriaBlocks.HEMLOCK.wood, 5, 20},
                //{TerrestriaBlocks.HEMLOCK.button, 5, 20},
                //{TerrestriaBlocks.HEMLOCK.door, 5, 20},
                //{TerrestriaBlocks.HEMLOCK.trapdoor, 5, 20},
                {TerrestriaBlocks.HEMLOCK.fence, 5, 20},
                {TerrestriaBlocks.HEMLOCK.fenceGate, 5, 20},
                //{TerrestriaBlocks.HEMLOCK.sign, 5, 20},
                //{TerrestriaBlocks.HEMLOCK.wallSign, 5, 20},
                //{TerrestriaBlocks.HEMLOCK.pressurePlate, 5, 20},
                //{TerrestriaBlocks.HEMLOCK.stairs, 5, 20},

                {TerrestriaBlocks.REDWOOD.leaves, 5, 20},
                {TerrestriaBlocks.REDWOOD.log, 5, 20},
                {TerrestriaBlocks.REDWOOD.planks, 5, 20},
                {TerrestriaBlocks.REDWOOD.slab, 5, 20},
                {TerrestriaBlocks.REDWOOD.strippedLog, 5, 20},
                {TerrestriaBlocks.REDWOOD.strippedWood, 5, 20},
                {TerrestriaBlocks.REDWOOD.wood, 5, 20},
                //{TerrestriaBlocks.REDWOOD.button, 5, 20},
                //{TerrestriaBlocks.REDWOOD.door, 5, 20},
                //{TerrestriaBlocks.REDWOOD.trapdoor, 5, 20},
                {TerrestriaBlocks.REDWOOD.fence, 5, 20},
                {TerrestriaBlocks.REDWOOD.fenceGate, 5, 20},
                //{TerrestriaBlocks.REDWOOD.sign, 5, 20},
                //{TerrestriaBlocks.REDWOOD.wallSign, 5, 20},
                //{TerrestriaBlocks.REDWOOD.pressurePlate, 5, 20},
                //{TerrestriaBlocks.REDWOOD.stairs, 5, 20},

                {TerrestriaBlocks.RUBBER.leaves, 5, 20},
                {TerrestriaBlocks.RUBBER.log, 5, 20},
                {TerrestriaBlocks.RUBBER.planks, 5, 20},
                {TerrestriaBlocks.RUBBER.slab, 5, 20},
                {TerrestriaBlocks.RUBBER.strippedLog, 5, 20},
                {TerrestriaBlocks.RUBBER.strippedWood, 5, 20},
                {TerrestriaBlocks.RUBBER.wood, 5, 20},
                //{TerrestriaBlocks.RUBBER.button, 5, 20},
                //{TerrestriaBlocks.RUBBER.door, 5, 20},
                //{TerrestriaBlocks.RUBBER.trapdoor, 5, 20},
                {TerrestriaBlocks.RUBBER.fence, 5, 20},
                {TerrestriaBlocks.RUBBER.fenceGate, 5, 20},
                //{TerrestriaBlocks.RUBBER.sign, 5, 20},
                //{TerrestriaBlocks.RUBBER.wallSign, 5, 20},
                //{TerrestriaBlocks.RUBBER.pressurePlate, 5, 20},
                //{TerrestriaBlocks.RUBBER.stairs, 5, 20},

                {TerrestriaBlocks.SAKURA.leaves, 5, 20},
                {TerrestriaBlocks.SAKURA.log, 5, 20},
                {TerrestriaBlocks.SAKURA.planks, 5, 20},
                {TerrestriaBlocks.SAKURA.slab, 5, 20},
                {TerrestriaBlocks.SAKURA.strippedLog, 5, 20},
                {TerrestriaBlocks.SAKURA.strippedWood, 5, 20},
                {TerrestriaBlocks.SAKURA.wood, 5, 20},
                //{TerrestriaBlocks.SAKURA.button, 5, 20},
                //{TerrestriaBlocks.SAKURA.door, 5, 20},
                //{TerrestriaBlocks.SAKURA.trapdoor, 5, 20},
                {TerrestriaBlocks.SAKURA.fence, 5, 20},
                {TerrestriaBlocks.SAKURA.fenceGate, 5, 20},
                //{TerrestriaBlocks.SAKURA.sign, 5, 20},
                //{TerrestriaBlocks.SAKURA.wallSign, 5, 20},
                //{TerrestriaBlocks.SAKURA.pressurePlate, 5, 20},
                //{TerrestriaBlocks.SAKURA.stairs, 5, 20},

                {TerrestriaBlocks.WILLOW.leaves, 5, 20},
                {TerrestriaBlocks.WILLOW.log, 5, 20},
                {TerrestriaBlocks.WILLOW.planks, 5, 20},
                {TerrestriaBlocks.WILLOW.slab, 5, 20},
                {TerrestriaBlocks.WILLOW.strippedLog, 5, 20},
                {TerrestriaBlocks.WILLOW.strippedWood, 5, 20},
                {TerrestriaBlocks.WILLOW.wood, 5, 20},
                //{TerrestriaBlocks.WILLOW.button, 5, 20},
                //{TerrestriaBlocks.WILLOW.door, 5, 20},
                //{TerrestriaBlocks.WILLOW.trapdoor, 5, 20},
                {TerrestriaBlocks.WILLOW.fence, 5, 20},
                {TerrestriaBlocks.WILLOW.fenceGate, 5, 20},
                //{TerrestriaBlocks.WILLOW.sign, 5, 20},
                //{TerrestriaBlocks.WILLOW.wallSign, 5, 20},
                //{TerrestriaBlocks.WILLOW.pressurePlate, 5, 20},
                //{TerrestriaBlocks.WILLOW.stairs, 5, 20},

                {TerrestriaBlocks.JAPANESE_MAPLE.leaves, 5, 20},
                {TerrestriaBlocks.JAPANESE_MAPLE.log, 5, 20},
                {TerrestriaBlocks.JAPANESE_MAPLE.planks, 5, 20},
                {TerrestriaBlocks.JAPANESE_MAPLE.slab, 5, 20},
                {TerrestriaBlocks.JAPANESE_MAPLE.strippedLog, 5, 20},
                {TerrestriaBlocks.JAPANESE_MAPLE.strippedWood, 5, 20},
                {TerrestriaBlocks.JAPANESE_MAPLE.wood, 5, 20},
                //{TerrestriaBlocks.JAPANESE_MAPLE.button, 5, 20},
                //{TerrestriaBlocks.JAPANESE_MAPLE.door, 5, 20},
                //{TerrestriaBlocks.JAPANESE_MAPLE.trapdoor, 5, 20},
                {TerrestriaBlocks.JAPANESE_MAPLE.fence, 5, 20},
                {TerrestriaBlocks.JAPANESE_MAPLE.fenceGate, 5, 20},
                //{TerrestriaBlocks.JAPANESE_MAPLE.sign, 5, 20},
                //{TerrestriaBlocks.JAPANESE_MAPLE.wallSign, 5, 20},
                //{TerrestriaBlocks.JAPANESE_MAPLE.pressurePlate, 5, 20},
                //{TerrestriaBlocks.JAPANESE_MAPLE.stairs, 5, 20},

                {TerrestriaBlocks.RAINBOW_EUCALYPTUS.leaves, 5, 20},
                {TerrestriaBlocks.RAINBOW_EUCALYPTUS.log, 5, 20},
                {TerrestriaBlocks.RAINBOW_EUCALYPTUS.planks, 5, 20},
                {TerrestriaBlocks.RAINBOW_EUCALYPTUS.slab, 5, 20},
                {TerrestriaBlocks.RAINBOW_EUCALYPTUS.strippedLog, 5, 20},
                {TerrestriaBlocks.RAINBOW_EUCALYPTUS.strippedWood, 5, 20},
                {TerrestriaBlocks.RAINBOW_EUCALYPTUS.wood, 5, 20},
                //{TerrestriaBlocks.RAINBOW_EUCALYPTUS.button, 5, 20},
                //{TerrestriaBlocks.RAINBOW_EUCALYPTUS.door, 5, 20},
                //{TerrestriaBlocks.RAINBOW_EUCALYPTUS.trapdoor, 5, 20},
                {TerrestriaBlocks.RAINBOW_EUCALYPTUS.fence, 5, 20},
                {TerrestriaBlocks.RAINBOW_EUCALYPTUS.fenceGate, 5, 20},
                //{TerrestriaBlocks.RAINBOW_EUCALYPTUS.sign, 5, 20},
                //{TerrestriaBlocks.RAINBOW_EUCALYPTUS.wallSign, 5, 20},
                //{TerrestriaBlocks.RAINBOW_EUCALYPTUS.pressurePlate, 5, 20},
                //{TerrestriaBlocks.RAINBOW_EUCALYPTUS.stairs, 5, 20},

                //{TerrestriaBlocks.CYPRESS_QUARTER_LOG, 5, 20},
                //{TerrestriaBlocks.HEMLOCK_QUARTER_LOG, 5, 20},
                //{TerrestriaBlocks.RAINBOW_EUCALYPTUS_QUARTER_LOG, 5, 20},
                //{TerrestriaBlocks.REDWOOD_QUARTER_LOG, 5, 20},
                //{TerrestriaBlocks.STRIPPED_CYPRESS_QUARTER_LOG, 5, 20},
                //{TerrestriaBlocks.STRIPPED_HEMLOCK_QUARTER_LOG, 5, 20},
                //{TerrestriaBlocks.STRIPPED_RAINBOW_EUCALYPTUS_QUARTER_LOG, 5, 20},
                //{TerrestriaBlocks.STRIPPED_REDWOOD_QUARTER_LOG, 5, 20},

                {TerrestriaBlocks.DARK_JAPANESE_MAPLE_LEAVES, 5, 20},
                {TerrestriaBlocks.JAPANESE_MAPLE_SHRUB_LEAVES, 5, 20},
                {TerrestriaBlocks.JUNGLE_PALM_LEAVES, 5, 20},

                {TerrestriaBlocks.INDIAN_PAINTBRUSH, 5, 20},
                {TerrestriaBlocks.MONSTERAS, 5, 20},

                //{TerrestriaBlocks.CYPRESS_SAPLING, 5, 20},
                //{TerrestriaBlocks.SAKURA_SAPLING, 5, 20},
                //{TerrestriaBlocks.DARK_JAPANESE_MAPLE_SAPLING, 5, 20},
                //{TerrestriaBlocks.HEMLOCK_SAPLING, 5, 20},
                //{TerrestriaBlocks.JAPANESE_MAPLE_SAPLING, 5, 20},
                //{TerrestriaBlocks.JAPANESE_MAPLE_SHRUB_SAPLING, 5, 20},
                //{TerrestriaBlocks.JUNGLE_PALM_SAPLING, 5, 20}

        };
    }

}
